category = "system"
tags = ["system", "windows", "forensics", "dfir", "execution", "malware"]
maintainer = "Nybble"
homepage = "https://github.com/libyal/libscca/blob/main/documentation/Windows%20Prefetch%20File%20(PF)%20format.asciidoc"
sample = ""
