category = "image"
tags = ["image", "medical", "dicom", "healthcare", "imaging"]
maintainer = "Nybble"
homepage = "https://dicom.nema.org/medical/dicom/current/output/chtml/part10/chapter_7.html"
sample = ""
