category = "filesystem"
tags = ["filesystem", "linux", "ext4", "forensics", "disk"]
maintainer = "Nybble"
homepage = "https://www.kernel.org/doc/html/latest/filesystems/ext4/globals.html"
sample = ""
